project_id = "zrvzcsdxbhzwfabvndbo"

[functions.ai-chat]
verify_jwt = false

[functions.generate-blog-summary]
verify_jwt = true

[functions.analyze-contact]
verify_jwt = true

[functions.send-newsletter]
verify_jwt = true

[functions.confirm-subscription]
verify_jwt = false
