project_id = "zrvzcsdxbhzwfabvndbo"

[functions.ai-chat]
verify_jwt = false

[functions.track-visitor]
verify_jwt = false

[functions.generate-blog-summary]
verify_jwt = true

[functions.analyze-contact]
verify_jwt = true

[functions.send-newsletter]
verify_jwt = true

[functions.confirm-subscription]
verify_jwt = false

[functions.fetch-security-news]
verify_jwt = false

[functions.generate-newsletter]
verify_jwt = true

[functions.generate-blog-insights]
verify_jwt = true

[functions.generate-response]
verify_jwt = true
